version: '3.6'
services:
  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: cut_the_bullshit_dev
    image: 'postgres:11-alpine'
    ports:
      - 5432:5432
    volumes:
      - './data/postgres:/var/lib/postgresql/data'

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/cut_the_bullshit_dev?sslmode=disable
    depends_on:
      - postgres
